// frontend/src/components/WordCard.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import Button from 'primevue/button'
import Tag from 'primevue/tag'
import type { Word, WordLevel } from '../types'

const props = defineProps<{
  word: Word
  index: number
  total: number
}>()

const emit = defineEmits<{
  rate: [level: WordLevel]
}>()

const flipped = ref(false)

// 換字就翻回正面
watch(() => props.word.id, () => {
  flipped.value = false
})

const listNames = computed(() => Object.keys(props.word.lists ?? {}))
const inflections = computed(() => props.word.inflections ?? [])
const hasDefinition = computed(() => Boolean(props.word.definition_zh || props.word.definition_en))

function toggleFlip() {
  flipped.value = !flipped.value
}
</script>

<template>
  <div class="word-card">
    <div class="card-header">
      <Tag :value="`難度 ${word.band}`" severity="secondary" />
      <span class="progress-count">{{ index + 1 }} / {{ total }}</span>
    </div>

    <button type="button" class="card-face" @click="toggleFlip">
      <template v-if="!flipped">
        <span class="word-text">{{ word.word }}</span>
        <span v-if="word.phonetic" class="phonetic">[{{ word.phonetic }}]</span>
        <span v-if="word.pos" class="pos">{{ word.pos }}</span>
        <span class="flip-hint">點一下翻面看釋義</span>
      </template>

      <template v-else>
        <span class="word-text-back">{{ word.word }}</span>
        <span v-if="word.definition_zh" class="definition-zh">{{ word.definition_zh }}</span>
        <span v-if="word.definition_en" class="definition-en">{{ word.definition_en }}</span>
        <span v-if="!hasDefinition" class="no-definition">這個字還沒有釋義資料</span>
        <span v-if="inflections.length" class="inflections">
          詞形變化：{{ inflections.join('、') }}
        </span>
        <span class="list-tags">
          <Tag v-for="name in listNames" :key="name" :value="name" severity="info" />
        </span>
      </template>
    </button>

    <div class="rate-row">
      <Button label="不會" severity="danger" outlined @click="emit('rate', 'unknown')" />
      <Button label="模糊" severity="warn" outlined @click="emit('rate', 'fuzzy')" />
      <Button label="會了" severity="success" outlined @click="emit('rate', 'known')" />
    </div>
  </div>
</template>

<style scoped>
.word-card {
  background: var(--p-surface-card);
  border: 1px solid var(--p-surface-border);
  border-radius: 12px;
  padding: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
}

.progress-count {
  font-size: 0.875rem;
  color: var(--p-text-muted-color);
}

.card-face {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 12px;
  width: 100%;
  min-height: 240px;
  padding: 24px 16px;
  border: 2px dashed var(--p-surface-border);
  border-radius: 12px;
  background: var(--p-surface-ground);
  color: inherit;
  font-family: inherit;
  cursor: pointer;
  text-align: center;
}

.card-face:hover {
  border-color: var(--p-primary-color);
}

.word-text {
  font-size: 2rem;
  font-weight: 700;
  word-break: break-word;
}

.word-text-back {
  font-size: 1.375rem;
  font-weight: 700;
  word-break: break-word;
}

.phonetic {
  font-size: 1.125rem;
  color: var(--p-text-muted-color);
}

.pos {
  font-size: 0.875rem;
  color: var(--p-text-muted-color);
}

.flip-hint {
  margin-top: 8px;
  font-size: 0.8125rem;
  color: var(--p-text-muted-color);
}

.definition-zh {
  font-size: 1.125rem;
  line-height: 1.6;
}

.definition-en {
  font-size: 1rem;
  line-height: 1.6;
  color: var(--p-text-muted-color);
}

.no-definition,
.inflections {
  font-size: 0.875rem;
  color: var(--p-text-muted-color);
}

.list-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  justify-content: center;
}

.rate-row {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 12px;
  margin-top: 20px;
}

.rate-row :deep(.p-button) {
  width: 100%;
}

@media (max-width: 480px) {
  .word-card {
    margin: 0 -16px;
    border-left: none;
    border-right: none;
    border-radius: 0;
  }

  .word-text {
    font-size: 1.75rem;
  }

  .rate-row {
    gap: 8px;
  }
}
</style>

// web/components/vocabulary/word-card.tsx
"use client";

import { useEffect, useState } from "react";
import { Volume2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useSpeech } from "@/hooks/use-speech";
import type { Word, WordLevel } from "@/lib/types";

const RATINGS: {
  level: WordLevel;
  label: string;
  className: string;
  testId: string;
}[] = [
  {
    level: "unknown",
    label: "不會",
    className:
      "border-rose-500/40 text-rose-700 hover:bg-rose-500/10 dark:text-rose-300",
    testId: "rate-unknown",
  },
  {
    level: "fuzzy",
    label: "模糊",
    className:
      "border-amber-500/40 text-amber-700 hover:bg-amber-500/10 dark:text-amber-300",
    testId: "rate-fuzzy",
  },
  {
    level: "known",
    label: "會了",
    className:
      "border-emerald-500/40 text-emerald-700 hover:bg-emerald-500/10 dark:text-emerald-300",
    testId: "rate-known",
  },
];

export function WordCard({
  word,
  index,
  total,
  pending,
  autoSpeak,
  onRate,
}: {
  word: Word;
  index: number;
  total: number;
  pending: boolean;
  autoSpeak: boolean;
  onRate: (level: WordLevel) => void;
}) {
  const [flipped, setFlipped] = useState(false);
  const { supported, speaking, speak } = useSpeech();

  // 換到新的字時自動唸一次。翻面狀態也要跟著重置，不然會看到上一張的背面。
  useEffect(() => {
    setFlipped(false);
    if (autoSpeak && supported) speak(word.word);
  }, [word.id, word.word, autoSpeak, supported, speak]);

  const listNames = Object.keys(word.lists ?? {});
  const inflections = word.inflections ?? [];
  const hasDefinition = Boolean(word.definition_zh || word.definition_en);

  return (
    <Card>
      <CardContent className="space-y-4">
        <div className="flex items-center justify-between gap-2">
          <Badge variant="secondary">難度 {word.band}</Badge>
          <div className="flex items-center gap-2">
            {supported ? (
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={`播放 ${word.word} 的發音`}
                data-testid="speak-word"
                className={speaking ? "text-primary" : undefined}
                onClick={() => speak(word.word)}
              >
                <Volume2 className="size-5" aria-hidden />
              </Button>
            ) : null}
            <span
              className="text-sm tabular-nums text-muted-foreground"
              data-testid="word-progress"
            >
              {index + 1} / {total}
            </span>
          </div>
        </div>

        <button
          type="button"
          onClick={() => setFlipped((value) => !value)}
          data-testid="word-face"
          className="flex min-h-56 w-full flex-col items-center justify-center gap-3 rounded-xl border-2 border-dashed border-border bg-muted/30 px-4 py-6 text-center transition-colors hover:border-primary/50 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
        >
          {flipped ? (
            <>
              <span className="text-xl font-bold break-words">{word.word}</span>
              {word.definition_zh ? (
                <span className="text-base leading-relaxed break-words">
                  {word.definition_zh}
                </span>
              ) : null}
              {word.definition_en ? (
                <span className="text-sm leading-relaxed text-muted-foreground break-words">
                  {word.definition_en}
                </span>
              ) : null}
              {hasDefinition ? null : (
                <span className="text-sm text-muted-foreground">
                  這個字還沒有釋義資料
                </span>
              )}
              {inflections.length > 0 ? (
                <span className="text-sm text-muted-foreground break-words">
                  詞形變化：{inflections.join("、")}
                </span>
              ) : null}
              {listNames.length > 0 ? (
                <span className="flex flex-wrap justify-center gap-1.5">
                  {listNames.map((name) => (
                    <Badge key={name} variant="outline">
                      {name}
                    </Badge>
                  ))}
                </span>
              ) : null}
            </>
          ) : (
            <>
              <span className="text-3xl font-bold break-words">{word.word}</span>
              {word.phonetic ? (
                <span className="text-lg text-muted-foreground break-words">
                  [{word.phonetic}]
                </span>
              ) : null}
              {word.pos ? (
                <span className="text-sm text-muted-foreground">{word.pos}</span>
              ) : null}
              <span className="pt-2 text-sm text-muted-foreground">
                點一下翻面看釋義
              </span>
            </>
          )}
        </button>

        <div className="grid grid-cols-3 gap-2" data-testid="rate-row">
          {RATINGS.map((rating) => (
            <Button
              key={rating.level}
              variant="outline"
              size="lg"
              disabled={pending}
              data-testid={rating.testId}
              className={`h-11 w-full ${rating.className}`}
              onClick={() => onRate(rating.level)}
            >
              {rating.label}
            </Button>
          ))}
        </div>
      </CardContent>
    </Card>
  );
}
